CASH = 1000
TICKERS = "AMZN GOOGL BAC DELL GOOG TSM LLY XOM PANW WFC ETN GM AXP SPOT ROIV TAL HBAN KEY KMI RF CVE JWN BZ AEO".split()
# TICKERS = "BZ KMI CVE".split()

START_DATE = "2024-01-02"

RSI_PERIOD = 14
RSI_UPPER = 70
RSI_LOWER = 30
TRAIL_PERC = 0.06

ATR_PERIOD = 14
ATR_LOOSE_MULTIPLIER = 3
ATR_STRICT_MULTIPLIER = 0.01
