CASH = 1000
START_DATE = "2024-02-02"

RSI_PERIOD = 6
RSI_UPPER = 70
RSI_LOWER = 30

ATR_PERIOD = 7
ATR_LOOSE_MULTIPLIER = 2
ATR_STRICT_MULTIPLIER = 0.009


NORMAL = "AMZN GOOGL BAC DELL GOOG TSM LLY XOM PANW WFC ETN GM AXP SPOT ROIV TAL HBAN KEY KMI RF CVE JWN BZ AEO K CABA AAPL SBUX AMD".split()
TICKERS = NORMAL
