CASH = 1000
TICKERS = "AMZN GOOGL BAC DELL GOOG TSM LLY XOM PANW WFC ETN GM AXP SPOT ROIV TAL HBAN KEY KMI RF CVE JWN BZ AEO".split()
# TICKERS = "BZ KMI CVE".split()

START_DATE = "2023-06-20"

RSI_PERIOD = 6
RSI_UPPER = 70
RSI_LOWER = 30

ATR_PERIOD = 7
ATR_LOOSE_MULTIPLIER = 2
ATR_STRICT_MULTIPLIER = 0.0075
