CASH = 1000
START_DATE = "2024-01-01"

BOLLINGER_PERIOD = 10
BOLLINGER_STD = 0.5
BOLLINGER_WIDTH_THRESHOLD = 0.03

RSI_PERIOD = 14
RSI_UPPER = 50
RSI_LOWER = 20

ATR_PERIOD = 14
ATR_MULTIPLER = 0.5


NORMAL = "AMZN GOOGL BAC DELL GOOG TSM LLY XOM PANW WFC ETN GM AXP SPOT ROIV TAL HBAN KEY KMI RF CVE JWN BZ AEO K CABA AAPL SBUX AMD".split()
TICKERS = NORMAL
