CASH = 1000
START_DATE = "2024-01-15"

BOLLINGER_PERIOD = 14
BOLLINGER_STD = 0.8
BOLLINGER_WIDTH_THRESHOLD = 0.07

RSI_PERIOD = 14
RSI_UPPER = 70
RSI_LOWER = 30

ATR_PERIOD = 14
ATR_MULTIPLER = 1.5

CASH_MULTIPLIER = 0.7


NORMAL = "AMZN GOOGL BAC DELL GOOG TSM LLY XOM PANW WFC ETN GM AXP SPOT ROIV TAL HBAN KEY KMI RF CVE JWN BZ AEO K CABA AAPL SBUX AMD".split()
TICKERS = "WFC"
