CASH = 1000
START_DATE = "2023-12-01"  # 6 months
TICKERS = "AMZN GOOGL BAC DELL GOOG TSM LLY XOM PANW WFC ETN GM AXP SPOT ROIV TAL HBAN KEY KMI RF CVE JWN BZ AEO".split()
RSI_PERIOD = 14
RSI_UPPER = 70
RSI_LOWER = 30
TRAIL_PERC = 0.05
